### PR TITLE
Export csv ou json aulas e salas

### PR DESCRIPTION
**Pull request by nnnnpiz**
export CSV / JSON and buttons

### CODE REVIEW

**Comment by nnnnpiz** [comment]
tudo ok

**Review by K3vinb5 — APPROVED** [review]
Seems good

**Comment by rodrigotimoteo** [comment]
[Implementar Json Save para tabela aulas e salas (5)](https://trello.com/c/3QKeOFhR/7-implementar-json-save-para-tabela-aulas-e-salas-5)

**Comment by rodrigotimoteo** [comment]
[Implementar Csv Save para tabela aulas e salas (5)](https://trello.com/c/XRw9hzMZ/9-implementar-csv-save-para-tabela-aulas-e-salas-5)

**Pull request merged**
